# Generated by Django 2.0.5 on 2019-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('option_a', models.CharField(max_length=32)),
                ('option_b', models.CharField(max_length=32)),
                ('option_c', models.CharField(max_length=32)),
                ('option_d', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=32)),
            ],
        ),
    ]
